# Generated by Django 4.2.7 on 2024-12-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=60)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('withdrawal_password', models.CharField(blank=True, max_length=100, null=True)),
                ('inviteCode', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('last_click_time', models.DateTimeField(blank=True, null=True)),
                ('vip_level', models.PositiveSmallIntegerField(choices=[(1, 'VIP 1'), (2, 'VIP 2'), (3, 'VIP 3'), (4, 'VIP 4')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='usermanager_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='register_set', to='auth.permission')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
    ]
