# Generated by Django 4.2.7 on 2024-12-24 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('todays_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('wallet_address', models.CharField(blank=True, max_length=50, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('referral_count', models.PositiveIntegerField(default=0)),
                ('referral_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('has_newbie_bonus', models.BooleanField(default=False)),
                ('referred_users', models.ManyToManyField(blank=True, related_name='referrers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
